server:
  port: 8082

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service


logging:
  level:
    org.springframework.cloud.gateway: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
