server:
  port: 8082

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: identity-auth-route
          uri: lb://identity-service
          predicates:
            - Path=/api/auth/**
        - id: identity-route
          uri: lb://identity-service
          predicates:
            - Path=/api/identity/**
        - id: inventory-route
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventory/**
        - id: product-route
          uri: lb://product-service
          predicates:
            - Path=/api/products/**
        - id: payment-route
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**
        - id: order-route
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**
        - id: sales-customers-route
          uri: lb://sales-service
          predicates:
            - Path=/api/customers/**
        - id: sales-invoices-route
          uri: lb://sales-service
          predicates:
            - Path=/api/invoices/**
        - id: hrm-employees-route
          uri: lb://hrm-service
          predicates:
            - Path=/api/employees/**
        - id: hrm-attendance-route
          uri: lb://hrm-service
          predicates:
            - Path=/api/attendance/**
        - id: hrm-leaves-route
          uri: lb://hrm-service
          predicates:
            - Path=/api/leaves/**
        - id: finance-accounts-route
          uri: lb://finance-service
          predicates:
            - Path=/api/accounts/**
        - id: finance-journal-route
          uri: lb://finance-service
          predicates:
            - Path=/api/journal-entries/**
        - id: finance-payroll-route
          uri: lb://finance-service
          predicates:
            - Path=/api/payroll/**
        - id: procurement-vendors-route
          uri: lb://procurement-service
          predicates:
            - Path=/api/vendors/**
        - id: procurement-purchase-orders-route
          uri: lb://procurement-service
          predicates:
            - Path=/api/purchase-orders/**
        - id: procurement-goods-received-route
          uri: lb://procurement-service
          predicates:
            - Path=/api/goods-received/**
        - id: reporting-route
          uri: lb://reporting-service
          predicates:
            - Path=/api/reports/**


app:
  jwt:
    secret: c29tZS1zZWNyZXQta2V5LXdoaWNoLWlzLWp3dC1zdWl0YWJsZQ==

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
