spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/erp_db
    username: postgres
    password: md1962km
    driver-classname: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

server:
  port: 8086

jwt:
  secret: c29tZS1zZWNyZXQta2V5LXdoaWNoLWlzLWp3dC1zdWl0YWJsZQ==

logging:
  level:
    org.hibernate.SQL: DEBUG