spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/erp_db
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:md1962km}
    driver-classname: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

server:
  port: 8086

jwt:
  secret: c29tZS1zZWNyZXQta2V5LXdoaWNoLWlzLWp3dC1zdWl0YWJsZQ==
  expiration-ms: 86400000

logging:
  level:
    org.hibernate.SQL: DEBUG