server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: identity-route
          uri: lb://identity-service
          predicates:
            - Path=/api/auth/**
            - Path=/api/identity/**
        - id: inventory-route
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventory/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            duplex: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/